/*
* generated by Xtext
*/
package fr.insa.petrinet.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PetrinetOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
