/*
 * generated by Xtext
 */
package fr.enseeiht.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PDL1UiModule extends fr.enseeiht.ui.AbstractPDL1UiModule {
	public PDL1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
