/*
* generated by Xtext
*/
package fr.enseeiht.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PDL1OutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
