/*
* generated by Xtext
*/
package fr.enseeiht;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PDL2UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.enseeiht.ui.internal.PDL2Activator.getInstance().getInjector("fr.enseeiht.PDL2");
	}
	
}
