/*
 * generated by Xtext
 */
package fr.enseeiht;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PDL1RuntimeModule extends fr.enseeiht.AbstractPDL1RuntimeModule {

}
