/*
 * generated by Xtext
 */
package fr.enseeiht.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PDL2UiModule extends fr.enseeiht.ui.AbstractPDL2UiModule {
	public PDL2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
