/*
 * generated by Xtext
 */
package fr.enseeiht.txt;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimplePDLRuntimeModule extends fr.enseeiht.txt.AbstractSimplePDLRuntimeModule {

}
