/*
 * generated by Xtext
 */
package fr.insa.petrinet.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.insa.petrinet.ui.internal.PetrinetActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PetrinetExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PetrinetActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PetrinetActivator.getInstance().getInjector(PetrinetActivator.FR_INSA_PETRINET_PETRINET);
	}
	
}
