/*
* generated by Xtext
*/
package fr.insa.petrinet.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.insa.petrinet.services.PetrinetGrammarAccess;

public class PetrinetParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PetrinetGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.insa.petrinet.parser.antlr.internal.InternalPetrinetParser createParser(XtextTokenStream stream) {
		return new fr.insa.petrinet.parser.antlr.internal.InternalPetrinetParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PetriNet";
	}
	
	public PetrinetGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PetrinetGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
