/*
 * generated by Xtext
 */
package fr.enseeiht.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.enseeiht.ui.internal.PDL1Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PDL1ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PDL1Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PDL1Activator.getInstance().getInjector(PDL1Activator.FR_ENSEEIHT_PDL1);
	}
	
}
