/*
 * generated by Xtext
 */
package be.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimplePDLUiModule extends be.ui.AbstractSimplePDLUiModule {
	public SimplePDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
