/*
* generated by Xtext
*/
package be.ui.contentassist;

import be.ui.contentassist.AbstractSimplePDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimplePDLProposalProvider extends AbstractSimplePDLProposalProvider {

}
