/*
* generated by Xtext
*/
package fr.insa.petrinet.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PetrinetAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/insa/petrinet/parser/antlr/internal/InternalPetrinet.tokens");
	}
}
