/*
 * generated by Xtext
 */
package fr.insa.petrinet;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PetrinetRuntimeModule extends fr.insa.petrinet.AbstractPetrinetRuntimeModule {

}
