/*
* generated by Xtext
*/
package fr.insa.petrinet.ui.contentassist;

import fr.insa.petrinet.ui.contentassist.AbstractPetrinetProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PetrinetProposalProvider extends AbstractPetrinetProposalProvider {

}
