/*
 * generated by Xtext
 */
package fr.insa.petrinet.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PetrinetUiModule extends fr.insa.petrinet.ui.AbstractPetrinetUiModule {
	public PetrinetUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
