/*
* generated by Xtext
*/
package be.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SimplePDLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
