/*
* generated by Xtext
*/
package fr.enseeiht.txt.ui.contentassist;

import fr.enseeiht.txt.ui.contentassist.AbstractSimplePDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimplePDLProposalProvider extends AbstractSimplePDLProposalProvider {

}
