/*
* generated by Xtext
*/
package fr.insa.petrinet;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PetrinetUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.insa.petrinet.ui.internal.PetrinetActivator.getInstance().getInjector("fr.insa.petrinet.Petrinet");
	}
	
}
